### ISSUE TITLE
Course list isn't complete

### ISSUE THREAD

**Issue by yvonne-yang** [UTM-Hacklab/VIAplanner#285]
Hey there, this is a terrific project! I had a problem with finding courses on your deployed website. Most UTSG courses do not show up in the search bar. When I built the code from source, not a single course showed up. I was wondering if you are doing web scraping or if there is a separate database that I need to set up? Any assistance would be appreciated:)!

**Screenshots**
![image](https://user-images.githubusercontent.com/60620007/123835155-36449f80-d8d6-11eb-96ac-cf2f8a54b572.png)
(Note how it skips from 'J' to 'V')

**Comment by TheFatPanda97** [comment]
Hey @yvonne-yang, to set up the frontend locally, you would need a .env file, I can send it to you via email if you want. In terms of why we don't have all of the UTSG courses, when I scraped it, they were not updated yet, but I could scrape it tonight and it should have all the updated courses. Unfortunately,  I won't be able to give you the .env file for the course scrapers since they contain our MongoDB credentials 😢

**Comment by yvonne-yang** [comment]
No worries, I'm happy as long as one option works. Let me know when you've scraped it. Thanks for the prompt response btw! It's great to see that this project is still actively being improved on:D

**Comment by TheFatPanda97** [comment]
Update on the course scraping, it turns out that the source we use for scraping (uoft course finder) is not the most updated, so we will be actively transitioning to other sources such as [art and sci timetable](https://timetable.iit.artsci.utoronto.ca/). I'll be closing this issue for now until further updates.
