### ISSUE TITLE
Allow conflicts

### ISSUE THREAD

**Issue by tsids** [UTM-Hacklab/VIAplanner#339]
Add a toggle that can let the user choose whether they would like conflicts or not. 

That way, the user could add all the courses they want and then readjust, instead of having the issue of not having the course on there in the first place.

**Comment by ggggg** [comment]
One possible implementation would be to add the course to the course list, but highlight it is not in the timetable due to no space (See image as example):
![image](https://github.com/VIAplanner/via-timetable/assets/25105662/d64099e9-4c8e-43d9-afd4-fb788311be3b)

**Comment by ggggg** [comment]
Related to #296, I think allowing conflicts to occur is a better solution.

**Comment by ggggg** [comment]
Conflicts are already an option but they are not enabled by default
![image](https://github.com/VIAplanner/via-timetable/assets/25105662/b76b8db6-7fee-4617-9f7e-113f44fa6477)
Since there are other issues better describing issues with the current implementation I will close this issue.
See #296, #344.
